/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

public class problem2 {
public static void main(String[] args){

	double h=0;  //think that h is first of sequence
	double y=1;  //y is after than h.
	double total=0; //total is our sum of even fibonacci numbers
	
	//  h<4m && y<4m is wrong because h can 3,9m so new h is exceed 4m 
	while(h+y+y<4000000){
	
	h=h+y; //  (first+second) give to us a new first
	//if new first is even, sum of total and h.  
	if(h%2==0){
		total=total+h;
}
	y=h+y; //  (new first+second) give to us a new second
	
	//again test new second is even or not.
	if(y%2==0){
		total=total+y;
	}
	
	}
	System.out.println(total); //sum of even numbers between 1 to 4m
	
	}
}